version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9000:80"
    environment:
      - APP_KEY=
      - APP_ENV=
      - APP_DEBUG=
      - DB_CONNECTION=
      - DB_HOST=
      - DB_PORT=
      - DB_DATABASE=
      - DB_USERNAME=
      - DB_PASSWORD=